[supabase]
url = "https://rwxettebcgohbcwzntke.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3eGV0dGViY2dvaGJjd3pudGtlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4ODAxNzg4OCwiZXhwIjoyMTAzNTkzODg4fQ.TboxFaCD45DU8i3glYgWLguOo-bbs6M-UBA8_RxtxLU"
voter_salt = "marcusisawhaleofabloke"